[package]
name = "dfelp"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
color-eyre = "0.6.2"
env_logger = "0.10.0"
log = "0.4.20"
reqwest = "0.11.20"
scraper = "0.17.1"
tokio = { version = "1.0", features = ["macros", "rt-multi-thread"] }

