name: Tests
env:
    CARGO_TERM_COLOR: always
    BOT_TOKEN: "TOKEN" 
    DEBUG_GUILD: 1234
    PG_USER: "root"
    PG_PASS: "postgres"
    PG_IP: "localhost"
    PG_PORT: 5432
    PG_DB_NAME: DB_NAME
    DATABASE_URL: "postgres://root:postgres@localhost:5432/postgres"
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: ${{ env.PG_USER }}
          POSTGRES_DATABASE: postgres
          POSTGRES_PASSWORD: ${{ env.PG_PASS }}
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
          
    strategy:
      matrix:
        toolchain:
          - stable
          - beta
          - nightly

    steps:
    - uses: actions/checkout@v3
    - run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}
    - name: build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
