name: Tests
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: PASS
          POSTGRES_HOST: localhost
          POSTGRES_IP: localhost
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
          
    strategy:
      matrix:
        toolchain:
          - stable
          - beta
          - nightly

    steps:
    - uses: actions/checkout@v3
      env:
          CARGO_TERM_COLOR: always
          BOT_TOKEN: "TOKEN" 
          DEBUG_GUILD: 1234
          PG_USER: "USERNAME"
          PG_PASS: "PASS"
          PG_IP: "localhost"
          PG_PORT: 5432
          PG_DB_NAME: "DB_NAME"
    - run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
